FROM azurebatchrendering/centos:latest

ARG MAYA_INSTALL_SAS

COPY installMaya2018.sh /tmp/installMaya2018.sh
COPY render2018.sh /usr/bin/render2018.sh

RUN sh /tmp/installMaya2018.sh $MAYA_INSTALL_SAS 