FROM azurebatchrendering/centos_maya2018update3:latest

ARG VRAY_INSTALL_SAS

COPY installVRay36004.sh /tmp/installVRay36004.sh
COPY vray_config2018.xml /tmp/vray/vray_config2018.xml
COPY VRayForMaya.module /usr/autodesk/mayaIO2018/modules/VRayForMaya.module
COPY vrayRenderer.xml /usr/autodesk/mayaIO2018/bin/rendererDesc/vrayRenderer.xml

RUN sh /tmp/installVRay36004.sh $VRAY_INSTALL_SAS